name: Restart Service on Push

on:
  push:
    branches:
      - main

jobs:
  restart_service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: |
          git pull origin main

      - name: Restart Service
        run: |
          curl -X POST --basic --user "${{ secrets.ALWAYSDATA_API_KEY }}:" "https://api.alwaysdata.com/v1/service/${{ secrets.ALWAYSDATA_SERVICE_ID }}/restart/"
