name: Restart Service on Push

on:
  push:
    branches:
      - main

jobs:
  update_and_restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull from Main Branch and Install Requirements via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALWAYSDATA_HOST }}
          username: ${{ secrets.ALWAYSDATA_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/dormbot/www/aiogram_alert_bot
            git pull origin main && pip install -r requirements.txt

      - name: Restart Service
        run: |
          curl -X POST --basic --user "${{ secrets.ALWAYSDATA_API_KEY }}:" "https://api.alwaysdata.com/v1/service/${{ secrets.ALWAYSDATA_SERVICE_ID }}/restart/"
